export const items = [
    {
        id: Math.random(),
        title: 'وجبة إفطار',
        description: 'وجبة إفطار',
        price: '50 جنيه',
        categoty: 'فطار',
        image: '/imgs/1.png',
    },
    {
        id: Math.random(),
        title: 'وجبة غذاء',
        description: 'وجبة غذاء',
        price: '265 جنيه',
        categoty: 'غذاء',
        image: '/imgs/2.png',
    },
    {
        id: Math.random(),
        title: 'وجبة عشاء',
        description: 'وجبة عشاء',
        price: '185 جنيه',
        categoty: 'عشاء',
        image: '/imgs/3.png',
    },
    {
        id: Math.random(),
        title: 'وجبة غذاء ممتاز',
        description: 'وجبة غذاء',
        price: '476 جنيه',
        categoty: 'غذاء',
        image: '/imgs/1.png',
    },
    {
        id: Math.random(),
        title: 'وجبة عشاء درجة أولى',
        description: 'وجبة عشاء',
        price: '270 جنيه',
        categoty: 'عشاء',
        image: '/imgs/2.png',
    },
    {
        id: Math.random(),
        title: 'وجبة إفطار',
        description: 'وجبة إفطار',
        price: '50 جنيه',
        categoty: 'فطار',
        image: '/imgs/3.png',
    },
    {
        id: Math.random(),
        title: 'وجبة سناكس',
        description: 'وجبة سناكس',
        price: '10 جنيه',
        categoty: 'سناكس',
        image: '/imgs/1.png',
    },
];